repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier (markdown)
        language: system
        entry: prettier --write
        types: [markdown]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
