#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

DOTFILES=$HOME/.dotfiles

# find the installers and run them iteratively
for file in $(find -H "$DOTFILES" -maxdepth 2 -name "install.sh" -not -path "*.git*")
do
  sh -c "${file}"
done
